package com.iconloop.iitpvault.domain.dao;

import java.util.Date;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_master_storage
 */
public class TMasterStorage {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.762+09:00", comments="Source field: t_master_storage.id")
    private Integer id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.767+09:00", comments="Source field: t_master_storage.did")
    private String did;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.768+09:00", comments="Source field: t_master_storage.recovery_key")
    private String recoveryKey;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.768+09:00", comments="Source field: t_master_storage.created")
    private Date created;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.767+09:00", comments="Source field: t_master_storage.id")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.767+09:00", comments="Source field: t_master_storage.id")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.767+09:00", comments="Source field: t_master_storage.did")
    public String getDid() {
        return did;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.768+09:00", comments="Source field: t_master_storage.did")
    public void setDid(String did) {
        this.did = did == null ? null : did.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.768+09:00", comments="Source field: t_master_storage.recovery_key")
    public String getRecoveryKey() {
        return recoveryKey;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.768+09:00", comments="Source field: t_master_storage.recovery_key")
    public void setRecoveryKey(String recoveryKey) {
        this.recoveryKey = recoveryKey == null ? null : recoveryKey.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.768+09:00", comments="Source field: t_master_storage.created")
    public Date getCreated() {
        return created;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.768+09:00", comments="Source field: t_master_storage.created")
    public void setCreated(Date created) {
        this.created = created;
    }
}