package com.iconloop.iitpvault.domain.dao;

import java.util.Date;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_storage_secret
 */
public class TStorageSecret {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.815+09:00", comments="Source field: t_storage_secret.id")
    private Integer id;

    /**
     * Database Column Remarks:
     *   email or sms
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.815+09:00", comments="Source field: t_storage_secret.auth_id")
    private String authId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.815+09:00", comments="Source field: t_storage_secret.shared_clue")
    private String sharedClue;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.815+09:00", comments="Source field: t_storage_secret.created")
    private Date created;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.815+09:00", comments="Source field: t_storage_secret.id")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.815+09:00", comments="Source field: t_storage_secret.id")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.815+09:00", comments="Source field: t_storage_secret.auth_id")
    public String getAuthId() {
        return authId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.815+09:00", comments="Source field: t_storage_secret.auth_id")
    public void setAuthId(String authId) {
        this.authId = authId == null ? null : authId.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.815+09:00", comments="Source field: t_storage_secret.shared_clue")
    public String getSharedClue() {
        return sharedClue;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.815+09:00", comments="Source field: t_storage_secret.shared_clue")
    public void setSharedClue(String sharedClue) {
        this.sharedClue = sharedClue == null ? null : sharedClue.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.815+09:00", comments="Source field: t_storage_secret.created")
    public Date getCreated() {
        return created;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-09-14T10:48:45.815+09:00", comments="Source field: t_storage_secret.created")
    public void setCreated(Date created) {
        this.created = created;
    }
}